### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by Jwminva** [MetaCorp/obsidian-augmented-canvas#5]
Not generating anything.

**Comment by latay** [comment]
Yea, same here.
Obsidian has been updated to v1.7.7, and unfortunately, the plugin doesn't work anymore.
I think it's a great idea to integrate AI with Canvas, and I’d love to use it!

Would it be possible to add support for custom LLMs, such as local ones, perhaps by connecting with tools like LM Studio? Additionally, having the option to switch between different OpenAI model versions within the plugin would be fantastic.

**Comment by MetaCorp** [comment]
Fixed in 0.1.20. I have also added gpt-4o model in the settings.

**Comment by latay** [comment]
I’ve just tested the new version, and it works flawlessly! Thank you for the update!
